// 単語データプール
const baseVocabDb = [
    // --- How用法特訓コーナー ---
    { id: 1001, word: "How much...?", meaning: "いくらですか", tag: "how" },
    { id: 1002, word: "How many...?", meaning: "いくつかの", tag: "how" },
    { id: 1003, word: "How old...?", meaning: "何歳ですか", tag: "how" },
    { id: 1004, word: "How long...?", meaning: "どのくらいの長さ", tag: "how" },
    { id: 1005, word: "How tall...?", meaning: "どのくらいの背丈", tag: "how" },
    { id: 1006, word: "How often...?", meaning: "どのくらいの頻度", tag: "how" },
    { id: 1007, word: "How far...?", meaning: "どのくらいの距離", tag: "how" },
    { id: 1008, word: "How about...?", meaning: "～はいかがですか", tag: "how" },
    { id: 1009, word: "How to use", meaning: "使い方", tag: "how" },
    
    // --- 4級・動詞コーナー ---
    { id: 2001, word: "go → went", meaning: "行く → 行った", tag: "verbs" },
    { id: 2002, word: "come → came", meaning: "来る → 来た", tag: "verbs" },
    { id: 2003, word: "have → had", meaning: "持っている → 持っていた", tag: "verbs" },
    { id: 2004, word: "make → made", meaning: "作る → 作った", tag: "verbs" },
    { id: 2005, word: "take → took", meaning: "取る → 取った", tag: "verbs" },
    { id: 2006, word: "see → saw", meaning: "見る → 見た", tag: "verbs" },
    { id: 2007, word: "buy → bought", meaning: "買う → 買った", tag: "verbs" },
    { id: 2008, word: "eat → ate", meaning: "食べる → 食べた", tag: "verbs" },
    { id: 2009, word: "run → ran", meaning: "走る → 走った", tag: "verbs" },
    { id: 2010, word: "say → said", meaning: "言う → 言った", tag: "verbs" },
    { id: 2011, word: "read → read", meaning: "読む → 読んだ", tag: "verbs" },
    { id: 2012, word: "write → wrote", meaning: "書く → 書いた", tag: "verbs" },
    { id: 2013, word: "speak → spoke", meaning: "話す → 話した", tag: "verbs" },
    { id: 2014, word: "know → knew", meaning: "知っている → 知っていた", tag: "verbs" },
    { id: 2015, word: "play → plays", meaning: "（主語がひとり・ひとつ・いっぴきのとき）遊ぶ", tag: "verbs" },
    { id: 2016, word: "study → studies", meaning: "（主語がひとり・ひとつ・いっぴきのとき/ies）勉強する", tag: "verbs" },
    { id: 2017, word: "watch → watches", meaning: "（主語がひとり・ひとつ・いっぴきのとき/es）見る", tag: "verbs" },
    { id: 2018, word: "have → has", meaning: "（主語がひとり・ひとつ・いっぴきのとき/不規則）持っている", tag: "verbs" },
    { id: 2019, word: "do → does", meaning: "（主語がひとり・ひとつ・いっぴきのとき/es）する", tag: "verbs" },
    { id: 2020, word: "wash → washes", meaning: "（主語がひとり・ひとつ・いっぴきのとき/es）洗う", tag: "verbs" },

    // --- 4級・形容詞コーナー ---
    { id: 3001, word: "beautiful", meaning: "美しい", tag: "adj" },
    { id: 3002, word: "difficult", meaning: "難しい", tag: "adj" },
    { id: 3003, word: "famous", meaning: "有名な", tag: "adj" },
    { id: 3004, word: "favorite", meaning: "大好きな", tag: "adj" },
    { id: 3005, word: "interesting", meaning: "面白い", tag: "adj" },
    { id: 3006, word: "ready", meaning: "準備ができた", tag: "adj" },
    { id: 3007, word: "special", meaning: "特別な", tag: "adj" },
    { id: 3008, word: "useful", meaning: "役に立つ", tag: "adj" },
    { id: 3009, word: "excited", meaning: "ワクワクして", tag: "adj" },
    { id: 3010, word: "popular", meaning: "人気のある", tag: "adj" },

    // --- 4級・名詞コーナー ---
    { id: 4001, word: "hospital", meaning: "病院", tag: "noun" },
    { id: 4002, word: "museum", meaning: "博物館", tag: "noun" },
    { id: 4003, word: "station", meaning: "駅", tag: "noun" },
    { id: 4004, word: "subject", meaning: "教科", tag: "noun" },
    { id: 4005, word: "future", meaning: "未来", tag: "noun" },
    { id: 4006, word: "hobby", meaning: "趣味", tag: "noun" },
    { id: 4007, word: "weather", meaning: "天気", tag: "noun" },
    { id: 4008, word: "concert", meaning: "音楽会", tag: "noun" },

    // --- 4級・前置詞コーナー ---
    { id: 5001, word: "under", meaning: "～の下に", tag: "prep" },
    { id: 5002, word: "between", meaning: "（2つの）間に", tag: "prep" },
    { id: 5003, word: "during", meaning: "～の間中に", tag: "prep" },
    { id: 5004, word: "before", meaning: "～の前に", tag: "prep" },
    { id: 5005, word: "after", meaning: "～の後に", tag: "prep" },
    { id: 5006, word: "through", meaning: "～を通り抜けて", tag: "prep" },
    { id: 5007, word: "against", meaning: "～に反対して", tag: "prep" },
    { id: 5008, word: "without", meaning: "～なしで", tag: "prep" },

    // --- 3級・動詞コーナー（★三単現の日本語訳にルール説明を追加しました） ---
    { id: 6001, word: "agree → agreed", meaning: "賛成する → 賛成した", tag: "verbs3" },
    { id: 6002, word: "believe → believed", meaning: "信じる → 信じた", tag: "verbs3" },
    { id: 6003, word: "borrow → borrowed", meaning: "借りる → 借りた", tag: "verbs3" },
    { id: 6004, word: "choose → chose", meaning: "選ぶ → 選んだ", tag: "verbs3" },
    { id: 6005, word: "decide → decided", meaning: "決める → 決めた", tag: "verbs3" },
    { id: 6006, word: "explain → explained", meaning: "説明する → 説明した", tag: "verbs3" },
    { id: 6007, word: "forget → forgot", meaning: "忘れる → 忘れた", tag: "verbs3" },
    { id: 6008, word: "grow → grew", meaning: "育つ → 育った", tag: "verbs3" },
    { id: 6009, word: "hope → hoped", meaning: "望む → 望んだ", tag: "verbs3" },
    { id: 6010, word: "invite → invited", meaning: "招待する → 招待した", tag: "verbs3" },
    { id: 6011, word: "receive → received", meaning: "受け取る → 受け取った", tag: "verbs3" },
    { id: 6012, word: "return → returned", meaning: "戻る → 戻った", tag: "verbs3" },
    { id: 6013, word: "save → saved", meaning: "救う → 救った", tag: "verbs3" },
    { id: 6014, word: "travel → traveled", meaning: "旅行する → 旅行した", tag: "verbs3" },
    { id: 6015, word: "worry → worries", meaning: "（主語がひとり・ひとつ・いっぴきのとき/ies）心配する", tag: "verbs3" },
    { id: 6016, word: "choose → chooses", meaning: "（主語がひとり・ひとつ・いっぴきのとき）選ぶ", tag: "verbs3" },
    { id: 6017, word: "grow → grows", meaning: "（主語がひとり・ひとつ・いっぴきのとき）育つ", tag: "verbs3" },
    { id: 6018, word: "forget → forgets", meaning: "（主語がひとり・ひとつ・いっぴきのとき）忘れる", tag: "verbs3" },

    // --- 3級・形容詞コーナー ---
    { id: 7001, word: "careful", meaning: "注意深い", tag: "adj3" },
    { id: 7002, word: "comfortable", meaning: "快適な、心地いい", tag: "adj3" },
    { id: 7003, word: "delicious", meaning: "とても美味しい", tag: "adj3" },
    { id: 7004, word: "expensive", meaning: "値段が高い", tag: "adj3" },
    { id: 7005, word: "foreign", meaning: "外国の", tag: "adj3" },
    { id: 7006, word: "healthy", meaning: "健康的な", tag: "adj3" },
    { id: 7007, word: "international", meaning: "国際的な", tag: "adj3" },
    { id: 7008, word: "necessary", meaning: "必要な", tag: "adj3" },
    { id: 7009, word: "nervous", meaning: "緊張して、不安で", tag: "adj3" },
    { id: 7010, word: "surprised", meaning: "驚いて", tag: "adj3" },

    // --- 3級・名詞コーナー ---
    { id: 8001, word: "activity", meaning: "活動", tag: "noun3" },
    { id: 8002, word: "airport", meaning: "空港", tag: "noun3" },
    { id: 8003, word: "century", meaning: "世紀（100ねんかん）", tag: "noun3" },
    { id: 8004, word: "company", meaning: "会社", tag: "noun3" },
    { id: 8005, word: "custom", meaning: "習慣、伝統", tag: "noun3" },
    { id: 8006, word: "environment", meaning: "環境", tag: "noun3" },
    { id: 8007, word: "experience", meaning: "経験", tag: "noun3" },
    { id: 8008, word: "government", meaning: "政府", tag: "noun3" },
    { id: 8009, word: "opinion", meaning: "意見", tag: "noun3" },
    { id: 8010, word: "reason", meaning: "理由", tag: "noun3" },

    // --- 3級・熟語特訓コーナー ---
    { id: 9001, word: "arrive at", meaning: "～に到着する", tag: "idiom3" },
    { id: 9002, word: "ask for", meaning: "～を求める", tag: "idiom3" },
    { id: 9003, word: "be crowded with", meaning: "～で混雑している", tag: "idiom3" },
    { id: 9004, word: "be different from", meaning: "～と違っている", tag: "idiom3" },
    { id: 9005, word: "be full of", meaning: "～でいっぱいだ", tag: "idiom3" },
    { id: 9006, word: "by the way", meaning: "ところで", tag: "idiom3" },
    { id: 9007, word: "check out", meaning: "～を調べる", tag: "idiom3" },
    { id: 9008, word: "find out", meaning: "知る、分かる", tag: "idiom3" },
    { id: 9009, word: "in a hurry", meaning: "急いで", tag: "idiom3" },
    { id: 9010, word: "look forward to", meaning: "～を楽しみに待つ", tag: "idiom3" }
];
